### PR TITLE
Revert Visitor Interface

### LINKED ISSUE #293: Revert to the simpler Visitor interface
#280 changed the interface to allow passing data between children and parents in a control AST. @sgpthomas and I discussed this and came to conclusion that we should revert to the simpler interface from before because (1) pattern matching over the control program, in the same way `ScheduleConflicts` does, is the more general way to do this, (2) An analysis, like live range analysis, should be implemented as a `analysis::`.

### PR DESCRIPTION
**Pull request by rachitnigam**
Fixes #293.

- Implement `analysis::LiveRangeAnalysis`.
- Revert interface of Visitor to disallow data passing.

### CODE REVIEW

**Review by sgpthomas — APPROVED** [review]
lgtm!

**Review by sgpthomas — CHANGES_REQUESTED** [review]
par doesn't deal with local register correctly

**Comment by rachitnigam** [comment]
@sgpthomas will take a look at this before merging. Some of the code, specifically the two pass approach to `par` is broken by this version.

**Review by sgpthomas — APPROVED** [review]

**Comment by sgpthomas** [comment]
I haven't fixed #314 yet. but the analysis handles the other problems correctly now. I think that we should merge this and then improve the live range analysis because other things depend upon this. @rachitnigam

**Comment by rachitnigam** [comment]
Sounds good to me.

**Pull request merged**
