### PR TITLE
run specific passes from command line

### PR DESCRIPTION
**Pull request by ViviYe**
added command line option 
--pass <pass-name> to run a specific pass
--listpasses to list all available passes

### CODE REVIEW

**Comment by rachitnigam** [comment]
Hey @ViviYe. Can you install [cargo clippy](https://github.com/rust-lang/rust-clippy) and run both `cargo fmt` and `cargo clippy` before pushing to branches?

**Comment by ViviYe** [comment]
done!

**Comment by rachitnigam** [comment]
Look, I'll review it later today.

**Comment by rachitnigam** [comment]
The `--list-passes` fails with:
```
⇒  ./target/debug/futil --list-passes
error: The following required arguments were not provided:
    <file>
    --libraries <libraries>...

USAGE:
    futil <file> --backend <backend> --libraries <libraries>... --list-passes --pass <pass>...

For more information try --help
```
I think `from_opts` might try to create the context before it gets to the line that print the passes. When `--list-passes` is given, you want to list all the passes and then return.

**Comment by ViviYe** [comment]
We made a hashmap of pass names and functions to run the passes. when the list-passes option is turned on we simply loop through all the keys of the hashmap. We need the context to create the hashmap : (. As an ugly alternative, we can just simply print out strings before even creating the context?

**Comment by rachitnigam** [comment]
Two suggestions to fix this problem:
- What happens if you make the `Box`ed function take context as an argument instead of capturing the context variable? Then you can instantiate the context _after_ you've checked the passes.
- Look into the [`required_unless`](https://github.com/TeXitoi/structopt/issues/57) flag for structopt parsing which will allow you to make the required arguments optional when `list-passes` is passed in. 

Stylistically, I also recommend changing the parsing of `"all"` to map it to the string of passes and then use the hashmap normally instead of having a special case for it.

**Comment by sgpthomas** [comment]
I think the problem isn't that we create the context too early. it's just that `structopt` is making the `file` argument always required. I think just `required_unless` should fix the problem.

**Comment by ViviYe** [comment]
I tried adding `required_unless = "listpasses"` for both library and file
and this is the error I got
`thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', calyx/src/cmdline.rs:23:15`(the line pub file: pathbuf)
I think this is caused by trying to unwrap the empty Pathbuf? 
Opts::from_args() will yell at me unless I change  Pathbuf to Option<Pathbuf>

**Comment by rachitnigam** [comment]
Try changing it to an `Option<PathBuf>` and use one of the library functions on `Option` to turn it into a `Result` type with the `errors::Error::InvalidFile` error when the option is `None.

**Comment by sgpthomas** [comment]
@rachitnigam can you clarify the stylistic comment for Vivi?

**Comment by rachitnigam** [comment]
Instead of having a special case for “all”, remap names to the vector of string corresponding to the passes that need to be run.

**Comment by rachitnigam** [comment]
@ViviYe any updates on this?

**Comment by ViviYe** [comment]
Sorry, I asked Sam several days ago because I am still kinda confused about what to do and he said he will try to figure out what is the best way to do this and let me know. So I moved to work on issue #114 for now. Should I talk to Sam and keep working on this?

**Comment by rachitnigam** [comment]
Let's finish this since the change isn't that big. Does my explanation of what to do make sense?

**Comment by ViviYe** [comment]
I am not sure if I understood completely. Should I still keep 'all' as the default but simply remove it from the hashmap. In main if the option is all, run all the passes from the hashmap?
Or should I just check if anything is matched at all, if not, run all the passes?

**Comment by rachitnigam** [comment]
When you’re given “all”, set opts.pass equal to a vector of strings that are the passes that should be run when all is set.

**Comment by ViviYe** [comment]
so before I even start processing the vector, I check if the first one is all and if so, I set the vector to be a vector of all pass names?

**Comment by ViviYe** [comment]
Sorry the tests failed after me trying to merge master into the branch and I panicked and created all the mess : ( 
I am now trying to check the first element of the vector and then check if it is "all". I am encountering a problem that opts.pass is not mutable so I cannot reassign its value. I got around it violently by creating a mutable pointer to opts.pass.. and reassign that pointer if the first thing in the vector is "all"... It works but I don't know if this is what I am supposed to do?

**Comment by rachitnigam** [comment]
Oh, that might have been too messy! I guess we can merge the original implementation where "all" is explicitly handled and try out a better way in the future.

**Comment by sgpthomas** [comment]
@ViviYe Looks like the reason that some of the tests are failing is because not all of the passes are being called correctly. I think probably the cleanest thing to do, is keep the special 'all' pass that you add to the hashmap (the way things were initially) and make sure all the passes are being called there in the right order. (Look at `main.rs` in master to find the right order). As always, don't hesitate to ask if you get confused! You can run all the tests locally with `runt` in the root directory btw.

**Comment by ViviYe** [comment]
I added all back and copied the order of passes from master main.rs. It still seems to fail test cases.. : (

**Comment by rachitnigam** [comment]
Are you sure? The tests pass here. Did you rebuilt the binary?

**Pull request merged**
