### PR TITLE
Interpreter

### PR DESCRIPTION
**Pull request by kwf37**
Right now there are rough signatures for each helper function we will need to implement. I have documented all function stubs. Here are a few notes:

- There is a toplevel `_eval` function that will call `eval_lib` for primitive components, or `eval_c` and `eval_s` (short for eval control and eval structure, respectively) for user-defined component.
- There is a `State` data structure that can store all of the state of a component- currently only allows registers as primitive state components, so it basically stores all register values in the component. Needs some helper functions
- The current big task is evaluating a single `enable` statement. This will likely require a custom structure graph traversal, and also injecting values from the component's inputs and state into the structure graph.
- Evaluation creates a new component state, and I think each evaluation step should only depend on the component's state, inputs, and enabled components.

### CODE REVIEW

**Comment by kwf37** [comment]
For testing/debugging I added a small repl that I will use to print out some info at different time steps. The repl can be run on the counter example by setting the backend to interpreter as follows: 
`cargo run -- tests/integration/counter.futil -l primitives/std.lib -b interpreter`

For now, it has very limited functionality.

**Comment by kwf37** [comment]
As it turns out we are not actually storing primitive parameters anywhere in a user-defined component. For now we are hacking this together by adding to the Component struct, but we should revisit this and clean it up more.

**Comment by kwf37** [comment]
Some notes that I ran into:

- I have two possible semantics for how to read outputs from a structure graph: 
    1. I can either take the final state and apply it to a fresh graph and then read the output ports
    2. I can save the results from the last structure graph that was run and read the outputs from that graph.

- Debugging was tricky without visualization, so next I think I will focus on debugging tools to make the interpreter clearer.

- `cargo run --  tests/interpreter/count3.futil -l primitives/std.lib -b interpreter -i tests/interpreter/count3.json` runs the count3 example, and it outputs 3 as expected. I am currently using semantics 1 above for reading outputs from an evaluation graph.

- Running the interpreter currently just evaluates a component, but I will try to switch it back to using the interactive REPL soon.

- Currently std_add, std_reg, and std_const are the only primitives that are implemented.

**Comment by kwf37** [comment]
Next tasks to take care of:

- [ ] Implement the rest of the primitives, and change their signatures on our branch so that they don't have the extra signals. (Vivi)

- [ ] Implement remaining control statements. (Vivi + Ken pair programming)

- [ ] Refactor Interpreter to be able to run one step at a time- this seems useful for debugging and visualizing the code. (Vivi + Ken)

- [ ] Set up better visualization for StructureGraph. This will help _significantly_ in debugging any interpreter issues that pop up, and seems generally useful.

**Comment by sampsyo** [comment]
Thanks for all these notes; this is cool! I'd be interested to hear more about that first bullet—I'm not 100% clear on what the difference is between just reading the final state vs. reconstructing a graph.

Debugging tools also certainly sounds very useful!

**Comment by rachitnigam** [comment]
Subsumed by #263.

**Pull request closed without merging**
