### PR TITLE
Try simplifying the Relay compiler

### PR DESCRIPTION
**Pull request by sampsyo**
This is an attempt at a drastic simplification of the Relay compiler structure that sheds a lot of baggage from the relay-aot scaffolding we used. In particular, the main thing is that I wanted to see if it would be productive to at least get started by just generating strings directly instead of having the level of indirection that generating a FuTIL AST imposes. I hope that this will make it easier to get started: **prioritizing short-term gain over long-term happiness**. I propose that we get started this way and, when it inevitably comes back to bite us, reintroduce some sort of AST at that point.

The compiler does not actually work yet in any sense, of course. But it can emit strings that kinda sorta look like FuTIL programs! For example, this Relay program:

    fn () {
      add(37, 5)
    }

Translates to this ""FuTIL program"":

    import "primitives/std.lib";
    component main() -> () {
      cells {
        const0 = prim std_const(32, 37);
        const1 = prim std_const(32, 5);
        add2 = prim std_add(32);
      }
      wires {

      }
      control {
        <read const0>
        <read const1>
        <run add2>
      }
    }

Obviously, we have a lot to figure out here: I have not generated real control statements and have not tried to figure out how to coalesce things into groups. Doing that will take some ingenuity to figure out how to build up the wiring incrementally—but perhaps these are problems that the Dahlia frontend has already solved so @rachitnigam and @sgpthomas might have some insights.

Anyway, if @ViviYe agrees this is a good way to go to start getting programs to run relatively quickly, let's merge it and go from here!

---

Semi-relatedly, I also did a little bit of refactoring of the example. Now there is one Python script you run that can compile three different examples—and hopefully more in the future. You can do this, for example:

    python3 example.py -r add

to dump out the Relay text format for the `add` example. Then omit the `-r` to see the generated FuTIL. I like this because I like to compare the two formats to get a clearer sense of what needs to be done.

Of course, someday in the future it would be nice to have one compiler script and individual Python files so we can feed these in as Runt tests. But this will do for now until we have something actually testable.

### CODE REVIEW

**Comment by ViviYe** [comment]
thank you so much for helping me with the setups!!! I think i understand how things are set up now!! I am wondering what will be a good next step for me? should I compile Futil from dahlia and see how the functions are supposed to look like in Futil and try to generate actual control statements? 😆

**Comment by sampsyo** [comment]
That seems like a great idea! I like the notion of looking at FuTIL code generated from simple Dahlia programs to get a feel for what we should be generating. For example, I wonder how big a program like `y = x + 1` would be...

If you haven’t already, it might be a good idea to learn how to run a FuTIL program (using Verilator). It’s a little tricky but the README is marginally helpful and feel free to ask for help!

There are a lot of medium-sized conceptual issues left unresolved in my mind. They are:

- Relay programs are functional in the sense that they return a value. Dahlia programs are imperative in the sense that their “output” just consists of updating a memory. To capture the output of a Relay program, we will probably want to somehow create a register/memory called `out` that we update at the end.
- We somehow have to create wires and groups that we can activate. That’s sort of the “soul” of a FuTIL program and I don’t yet have a clear notion of how to do that.
- We’re currently only dealing with scalars (i.e., individual integers). Of course, TVM is for dealing with big tensors! We will need to do something to cope with `x + y` when `x` and `y` are both matrices or whatever. Presumably in parallel?
- I’ve disabled all optimizations. Eventually we should try enabling TVM optimizations and seeing if we can cope with the resulting code.

I think the right next steps are (a) figuring out how to generate wires/groups, and (b) sorting out the `out` thing for output. Both of those can take inspiration from the Dahlia-generated code! I think you should forge ahead with any crazy hack you can think of to make a complete small program work. And meanwhile I will also try to think of clever ways to go about this in general...

Somewhere in there, we can merge the branch into `master` and make little “feature branches” focused on individual improvements.

**Comment by ViviYe** [comment]
Thank you so much!!! I didn't quite understand the out part. Does that mean everytime we do a function call, we'll have to use a out register to store the function output?

**Comment by sampsyo** [comment]
Yeah, exactly. The thing is that FuTIL does not have a notion of "output" or "return values." So we have to do _something_ with the return value of a Relay program… and putting it in a register seems like the right thing to do.

**Pull request merged**
