### PR TITLE
Generate if-else assignments

### PR DESCRIPTION
**Pull request by rachitnigam**
Attempt to turn:
```
x = g1 ? y1;
x = g2 ? y2;
```

into
```
always_comb begin
...
  if g1
    x = y1;
  else if
    x = y2;
  else
    x = '0;
...
end
```

Changes in codegen:
- Generate `logic` instead of `wire`
- Generate a surrounding `always_comb` block.
- Don't generate `assign` expressions.

## To check
Make sure that ternary expressions using `assign` have the same semantics as
`x = y` statements under `always_comb` blocks. Specifically, make sure we're
not inferring latches or flip-flops.

## Test performed
Simulated `sample.futil` which takes 291 cycles before and after this commit.

### CODE REVIEW

**Comment by sgpthomas** [comment]
using `logic` makes me generally uncomfortable because it seems very easy to accidentally generate latches when we don't want them. Is there a way to avoid this? or some other way to guarantee that we are not generating latches?

**Comment by rachitnigam** [comment]
SystemVerilog doesn't generate latches unless you use `always_latch`: https://stackoverflow.com/questions/23101717/difference-among-always-ff-always-comb-always-latch-and-always

**Comment by rachitnigam** [comment]
Also, wire values can be latched anyways. The keyword wire doesn’t guarantee that things would be synthesized as wire.

**Comment by sgpthomas** [comment]
I hate everything

**Pull request merged**
