### PR TITLE
[mlir-dialect] Add MLIR dialect sketch-up.

### PR DESCRIPTION
**Pull request by cgyurgyik**
This is a potential skeleton for adding a MLIR dialect for FuTIL (following closely the example provided by MLIR). It contains a single operation ```add```.

As mentioned by @rachitnigam , the next steps would be to add some more operations and types so that guarded assignments (i.e. within a ```group```) can be written. This is a good place to discuss what exactly this may consist of.

### CODE REVIEW

**Comment by rachitnigam** [comment]
This looks really cool! Pre-merge, I'd like someone (me or @sgpthomas) to try to build it locally.

**Comment by cgyurgyik** [comment]
Sure, I won't merge anything until approved. I am also open to any questions or suggestions, as this is something relatively new for me.

Let me know if you need more information about building it. My README assumes you already have MLIR / LLVM, but that may be an unfair assumption.

**Comment by rachitnigam** [comment]
It would be useful to document how to get MLIR setup will minimal dependencies.

**Comment by cgyurgyik** [comment]
> It would be useful to document how to get MLIR setup will minimal dependencies.

Done.

**Comment by rachitnigam** [comment]
@sgpthomas were you able to build this branch? Should we merge this?

**Comment by cgyurgyik** [comment]
He wasn't, and I don't think we should merge it yet. I'd need to make sure it was up to date with current MLIR. I'm going to close this for now, and can come back to it in the future.

**Pull request closed without merging**
